### ISSUE TITLE
Fix pre-commit action

### ISSUE THREAD

**Issue by EnricoMi** [PyGithub/PyGithub#3058]
docformatter hook can't run with pre-commit 4 due to https://github.com/PyCQA/docformatter/pull/287

pre-commit action cannot specify pre-commit version.
pre-commit action is also readily replaced with a single `run`:

```yaml
run: |
  pip install 'pre-commit<4'
  pre-commit run --all-files --show-diff-on-failure --color=always
```

(plus cache, if you want it)

_Originally posted by @minrk in https://github.com/PyGithub/PyGithub/issues/3056#issuecomment-2401725893_

**Comment by minrk** [comment]
> What extra does that action bring other than invoking pre-commit directly?

Nothing, really. The whole thing is [here](https://github.com/pre-commit/action/blob/main/action.yml).

The only thing it adds is [caching the pre-commit envs](https://github.com/pre-commit/action/blob/576ff52938d158a24ac7e009dfa94b1455e7df99/action.yml#L15-L18), which you can keep with:

```yaml
  - uses: actions/cache@v4
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
```

If you want to fully replicate the precommit action (with pinning pre-commit<4 for now), replace it with:

```yaml
  - run: python -m pip install 'pre-commit<4'
  - run: python -m pip freeze --local
  - uses: actions/cache@v4
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
  - run: pre-commit run --show-diff-on-failure --color=always --all-files
```
